### ISSUE TITLE
Server Guide Banner

### ISSUE THREAD

**Issue by xdCoolesding** [revanced/revanced-branding#14]
It seems as the banner at the top of the Server Guide sections is still not rebranded to the new logo.
![Screenshot_20230607_143539](https://github.com/revanced/revanced-branding/assets/71647195/ac8b5d55-3a8d-4a69-9beb-1218efd85d32)

**Comment by oSumAtrIX** [comment]
![image](https://github.com/revanced/revanced-branding/assets/13122796/60b6901e-f124-4cfc-a155-876a73f834e0)

Fixed.
