### ISSUE TITLE
bug: unnecessary padding around the logo in some variants

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-branding#22]
## Issue
[ReVanced Logo Shape Dark](https://github.com/ReVanced/revanced-branding/blob/main/assets/revanced-logo/revanced-logo-shape-dark.svg) and [ReVanced Logo Shape Light](https://github.com/ReVanced/revanced-branding/blob/main/assets/revanced-logo/revanced-logo-shape-light.svg) have unnecessary padding around the logos

This padding does not exist on the regular [ReVanced Logo Shape](https://github.com/ReVanced/revanced-branding/blob/main/assets/revanced-logo/revanced-logo-shape.svg) variant

This makes it impossible to use as an icon in frontend, as no-matter where you place the icon it will barely be visible due to how small it actually is

**Comment by oSumAtrIX** [comment]
If we remove the padding, how will you match the correct padding when you need it?

**Comment by Ushie** [comment]
I also don't see anything related to padding in the Branding Guidelines

**Comment by oSumAtrIX** [comment]
The padding was kept with full intention because it retains the original logos padding which, when not kept, would be not possible to "guess", whereas removing the padding, like you said, you require additional modification regardless, can be done.

**Comment by Ushie** [comment]
When would the original logo padding ever be needed for this variant? because an instance like that sounds like it should be using the full logo.
