### ISSUE TITLE
Add monochromatic ReVanced logo shape files

### ISSUE THREAD

**Issue by xafn** [revanced/revanced-branding#5]
## Issue
There are no flat-coloured versions of the logo shape.

## Solution
Add them.

## Motivation
This would be useful when people are including ReVanced in icon packs or any flat design related media.

**Comment by oSumAtrIX** [comment]
Can you elaborate further, on what you mean by "flat-colored"?

**Comment by xafn** [comment]
Oh wait these were  always here lmao I didn't see them:
https://github.com/revanced/revanced-branding/blob/dev/assets/revanced-logo/revanced-logo-shape-dark.svg
https://github.com/revanced/revanced-branding/blob/dev/assets/revanced-logo/revanced-logo-shape-light.svg
